// js/packages/docusaurus-pagefind/src/theme/SearchBar/Search.jsx
import { useState, useEffect } from "react";
import useDocusaurusContext from "@docusaurus/useDocusaurusContext";

export default function Search() {
  const { siteConfig } = useDocusaurusContext();
  const [path, setPath] = useState("");

  useEffect(() => {
    setPath(`${siteConfig.baseUrl}pagefind/pagefind.js`);
  }, [siteConfig]);

  useEffect(() => {
    import("@getcanary/web/components/canary-root");
    import("@getcanary/web/components/canary-provider-pagefind");
    import("@getcanary/web/components/canary-modal");
    import("@getcanary/web/components/canary-trigger-searchbar");
    import("@getcanary/web/components/canary-content");
    import("@getcanary/web/components/canary-search");
    import("@getcanary/web/components/canary-search-input");
    import("@getcanary/web/components/canary-search-results");
  }, []);

  if (!path) {
    return null;
  }

  return (
    <canary-root framework="docusaurus">
      <canary-provider-pagefind path={path}>
        <canary-modal>
          <canary-trigger-searchbar slot="trigger"></canary-trigger-searchbar>
          <canary-content slot="content">
            <canary-search slot="search">
              <canary-search-input slot="input"></canary-search-input>
              <canary-search-results slot="results"></canary-search-results>
            </canary-search>
          </canary-content>
        </canary-modal>
      </canary-provider-pagefind>
    </canary-root>
  );
}

// js/apps/docs/components/Search.vue
<script setup lang="ts">
import { onMounted } from "vue";

onMounted(async () => {
  import("@getcanary/web/components/canary-styles-default");
  import("@getcanary/web/components/canary-provider-mock");
  import("@getcanary/web/components/canary-modal");
  import("@getcanary/web/components/canary-trigger-searchbar");
  import("@getcanary/web/components/canary-content");
  import("@getcanary/web/components/canary-search");
  import("@getcanary/web/components/canary-search-input");
  import("@getcanary/web/components/canary-search-results");
  import("@getcanary/web/components/canary-ask");
  import("@getcanary/web/components/canary-ask-input");
  import("@getcanary/web/components/canary-ask-results");
});
</script>

<template>
  <div class="px-8 w-[320px]">
    <canary-styles-default framework="vitepress">
      <canary-provider-mock>
        <canary-modal>
          <canary-trigger-searchbar slot="trigger"></canary-trigger-searchbar>
          <canary-content slot="content">
            <canary-search slot="search">
              <canary-search-input slot="input"></canary-search-input>
              <canary-search-results slot="results"></canary-search-results>
            </canary-search>
            <canary-ask slot="ask">
              <canary-ask-input slot="input"></canary-ask-input>
              <canary-ask-results slot="results"></canary-ask-results>
            </canary-ask>
          </canary-content>
        </canary-modal>
      </canary-provider-mock>
    </canary-styles-default>
  </div>
</template>
